### ISSUE TITLE
Stability and tuning needed

### ISSUE THREAD

**Issue by dorimanx** [zanezam/cpufreq-governor-zzmoove#1]
Hi,
issue #1
My users report that if gov is used when device is in deep sleep, some times they get SOD, device stuck and no response.
When other gov used, all OK.

issue #2
Gov is very aggressive on freq jump to max on idle.
example.
system is idle, not much running, but i see that freq is jumping from 300 to 1400/1500Mhz and not hovering 200 to 500 as other govs do...

So it's GOOD for fast response, but BAD for battery and CPU heat, as on OC CPU heatup fast, and on idle device is warm.

If you will have time to look for possible problems, it's will be very nice!
many users like your GOV :)

**Comment by zanezam** [comment]
Hi dorimanx

thx for reporting! of course i will look into this and try to fix it but currently i am hunting a other bug in a 0.7c version ;) may i ask when these problems began? since current version 0.7b or since any previous version? DFS and Legacy mode compiled in? and which settings do you provide your users? The "problem" is i never (well except with some prototype hotplug-versions _g_) had SOD's and no reports of any on samsung stock based kernel (boeffla) which i use and also not in any other kernel threads i am having an eye on (well i forgot yours though _g_). yes I must admit scaling ever was and still is a bit aggressive on idle thats something i want to "fix" for some time now, i waited if recent changes from Yank555 in scaling logic calms down that but it obviously did not really change anything regarding this. hotplugging is now calmed i will see if i can do that with scaling in addition ;) will check that behaving as part of my current bug hunting too ;) ehm one quick suggestion pops up im my mind: can u give your "SOD users" the advice to halfen the sampling rate sleep multiplier to 2 and see if that change something?

cheers
ZZ

**Comment by dorimanx** [comment]
problems started at 0.7 version, i think...
ok, i will ask to do more tests, as you requested.

**Comment by zanezam** [comment]
issues should be fixed in current version 0.8
